// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.nuxie.flutter.nativeplugin

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NuxieBridgePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class PConfigureRequest (
  val apiKey: String? = null,
  val wrapperVersion: String? = null,
  val usingPurchaseController: Boolean? = null,
  val environment: String? = null,
  val apiEndpoint: String? = null,
  val logLevel: String? = null,
  val enableConsoleLogging: Boolean? = null,
  val enableFileLogging: Boolean? = null,
  val redactSensitiveData: Boolean? = null,
  val retryCount: Long? = null,
  val retryDelaySeconds: Long? = null,
  val eventBatchSize: Long? = null,
  val flushAt: Long? = null,
  val flushIntervalSeconds: Long? = null,
  val maxQueueSize: Long? = null,
  val maxCacheSizeBytes: Long? = null,
  val cacheExpirationSeconds: Long? = null,
  val featureCacheTtlSeconds: Long? = null,
  val localeIdentifier: String? = null,
  val isDebugMode: Boolean? = null,
  val eventLinkingPolicy: String? = null,
  val maxFlowCacheSizeBytes: Long? = null,
  val flowCacheExpirationSeconds: Long? = null,
  val maxConcurrentFlowDownloads: Long? = null,
  val flowDownloadTimeoutSeconds: Long? = null,
  val purchaseTimeoutSeconds: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PConfigureRequest {
      val apiKey = pigeonVar_list[0] as String?
      val wrapperVersion = pigeonVar_list[1] as String?
      val usingPurchaseController = pigeonVar_list[2] as Boolean?
      val environment = pigeonVar_list[3] as String?
      val apiEndpoint = pigeonVar_list[4] as String?
      val logLevel = pigeonVar_list[5] as String?
      val enableConsoleLogging = pigeonVar_list[6] as Boolean?
      val enableFileLogging = pigeonVar_list[7] as Boolean?
      val redactSensitiveData = pigeonVar_list[8] as Boolean?
      val retryCount = pigeonVar_list[9] as Long?
      val retryDelaySeconds = pigeonVar_list[10] as Long?
      val eventBatchSize = pigeonVar_list[11] as Long?
      val flushAt = pigeonVar_list[12] as Long?
      val flushIntervalSeconds = pigeonVar_list[13] as Long?
      val maxQueueSize = pigeonVar_list[14] as Long?
      val maxCacheSizeBytes = pigeonVar_list[15] as Long?
      val cacheExpirationSeconds = pigeonVar_list[16] as Long?
      val featureCacheTtlSeconds = pigeonVar_list[17] as Long?
      val localeIdentifier = pigeonVar_list[18] as String?
      val isDebugMode = pigeonVar_list[19] as Boolean?
      val eventLinkingPolicy = pigeonVar_list[20] as String?
      val maxFlowCacheSizeBytes = pigeonVar_list[21] as Long?
      val flowCacheExpirationSeconds = pigeonVar_list[22] as Long?
      val maxConcurrentFlowDownloads = pigeonVar_list[23] as Long?
      val flowDownloadTimeoutSeconds = pigeonVar_list[24] as Long?
      val purchaseTimeoutSeconds = pigeonVar_list[25] as Long?
      return PConfigureRequest(apiKey, wrapperVersion, usingPurchaseController, environment, apiEndpoint, logLevel, enableConsoleLogging, enableFileLogging, redactSensitiveData, retryCount, retryDelaySeconds, eventBatchSize, flushAt, flushIntervalSeconds, maxQueueSize, maxCacheSizeBytes, cacheExpirationSeconds, featureCacheTtlSeconds, localeIdentifier, isDebugMode, eventLinkingPolicy, maxFlowCacheSizeBytes, flowCacheExpirationSeconds, maxConcurrentFlowDownloads, flowDownloadTimeoutSeconds, purchaseTimeoutSeconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      wrapperVersion,
      usingPurchaseController,
      environment,
      apiEndpoint,
      logLevel,
      enableConsoleLogging,
      enableFileLogging,
      redactSensitiveData,
      retryCount,
      retryDelaySeconds,
      eventBatchSize,
      flushAt,
      flushIntervalSeconds,
      maxQueueSize,
      maxCacheSizeBytes,
      cacheExpirationSeconds,
      featureCacheTtlSeconds,
      localeIdentifier,
      isDebugMode,
      eventLinkingPolicy,
      maxFlowCacheSizeBytes,
      flowCacheExpirationSeconds,
      maxConcurrentFlowDownloads,
      flowDownloadTimeoutSeconds,
      purchaseTimeoutSeconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PConfigureRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PTriggerRequest (
  val requestId: String? = null,
  val event: String? = null,
  val properties: Map<String?, Any?>? = null,
  val userProperties: Map<String?, Any?>? = null,
  val userPropertiesSetOnce: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PTriggerRequest {
      val requestId = pigeonVar_list[0] as String?
      val event = pigeonVar_list[1] as String?
      val properties = pigeonVar_list[2] as Map<String?, Any?>?
      val userProperties = pigeonVar_list[3] as Map<String?, Any?>?
      val userPropertiesSetOnce = pigeonVar_list[4] as Map<String?, Any?>?
      return PTriggerRequest(requestId, event, properties, userProperties, userPropertiesSetOnce)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      event,
      properties,
      userProperties,
      userPropertiesSetOnce,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PTriggerRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PTriggerUpdate (
  val requestId: String? = null,
  val updateKind: String? = null,
  val payload: Map<String?, Any?>? = null,
  val isTerminal: Boolean? = null,
  val timestampMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PTriggerUpdate {
      val requestId = pigeonVar_list[0] as String?
      val updateKind = pigeonVar_list[1] as String?
      val payload = pigeonVar_list[2] as Map<String?, Any?>?
      val isTerminal = pigeonVar_list[3] as Boolean?
      val timestampMs = pigeonVar_list[4] as Long?
      return PTriggerUpdate(requestId, updateKind, payload, isTerminal, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      updateKind,
      payload,
      isTerminal,
      timestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PTriggerUpdate) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PFeatureAccess (
  val allowed: Boolean? = null,
  val unlimited: Boolean? = null,
  val balance: Long? = null,
  val type: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PFeatureAccess {
      val allowed = pigeonVar_list[0] as Boolean?
      val unlimited = pigeonVar_list[1] as Boolean?
      val balance = pigeonVar_list[2] as Long?
      val type = pigeonVar_list[3] as String?
      return PFeatureAccess(allowed, unlimited, balance, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      allowed,
      unlimited,
      balance,
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PFeatureAccess) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PFeatureCheckResult (
  val customerId: String? = null,
  val featureId: String? = null,
  val requiredBalance: Long? = null,
  val code: String? = null,
  val allowed: Boolean? = null,
  val unlimited: Boolean? = null,
  val balance: Long? = null,
  val type: String? = null,
  val preview: Any? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PFeatureCheckResult {
      val customerId = pigeonVar_list[0] as String?
      val featureId = pigeonVar_list[1] as String?
      val requiredBalance = pigeonVar_list[2] as Long?
      val code = pigeonVar_list[3] as String?
      val allowed = pigeonVar_list[4] as Boolean?
      val unlimited = pigeonVar_list[5] as Boolean?
      val balance = pigeonVar_list[6] as Long?
      val type = pigeonVar_list[7] as String?
      val preview = pigeonVar_list[8]
      return PFeatureCheckResult(customerId, featureId, requiredBalance, code, allowed, unlimited, balance, type, preview)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      customerId,
      featureId,
      requiredBalance,
      code,
      allowed,
      unlimited,
      balance,
      type,
      preview,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PFeatureCheckResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PFeatureUsageResult (
  val success: Boolean? = null,
  val featureId: String? = null,
  val amountUsed: Double? = null,
  val message: String? = null,
  val usageCurrent: Double? = null,
  val usageLimit: Double? = null,
  val usageRemaining: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PFeatureUsageResult {
      val success = pigeonVar_list[0] as Boolean?
      val featureId = pigeonVar_list[1] as String?
      val amountUsed = pigeonVar_list[2] as Double?
      val message = pigeonVar_list[3] as String?
      val usageCurrent = pigeonVar_list[4] as Double?
      val usageLimit = pigeonVar_list[5] as Double?
      val usageRemaining = pigeonVar_list[6] as Double?
      return PFeatureUsageResult(success, featureId, amountUsed, message, usageCurrent, usageLimit, usageRemaining)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      featureId,
      amountUsed,
      message,
      usageCurrent,
      usageLimit,
      usageRemaining,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PFeatureUsageResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PProfileResponse (
  val raw: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PProfileResponse {
      val raw = pigeonVar_list[0] as Map<String?, Any?>?
      return PProfileResponse(raw)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      raw,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PProfileResponse) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PFeatureAccessChangedEvent (
  val featureId: String? = null,
  val from: PFeatureAccess? = null,
  val to: PFeatureAccess? = null,
  val timestampMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PFeatureAccessChangedEvent {
      val featureId = pigeonVar_list[0] as String?
      val from = pigeonVar_list[1] as PFeatureAccess?
      val to = pigeonVar_list[2] as PFeatureAccess?
      val timestampMs = pigeonVar_list[3] as Long?
      return PFeatureAccessChangedEvent(featureId, from, to, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      featureId,
      from,
      to,
      timestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PFeatureAccessChangedEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PFlowLifecycleEvent (
  val type: String? = null,
  val flowId: String? = null,
  val reason: String? = null,
  val timestampMs: Long? = null,
  val payload: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PFlowLifecycleEvent {
      val type = pigeonVar_list[0] as String?
      val flowId = pigeonVar_list[1] as String?
      val reason = pigeonVar_list[2] as String?
      val timestampMs = pigeonVar_list[3] as Long?
      val payload = pigeonVar_list[4] as Map<String?, Any?>?
      return PFlowLifecycleEvent(type, flowId, reason, timestampMs, payload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      flowId,
      reason,
      timestampMs,
      payload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PFlowLifecycleEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PLogEvent (
  val level: String? = null,
  val message: String? = null,
  val scope: String? = null,
  val timestampMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PLogEvent {
      val level = pigeonVar_list[0] as String?
      val message = pigeonVar_list[1] as String?
      val scope = pigeonVar_list[2] as String?
      val timestampMs = pigeonVar_list[3] as Long?
      return PLogEvent(level, message, scope, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      level,
      message,
      scope,
      timestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PLogEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PPurchaseRequest (
  val requestId: String? = null,
  val platform: String? = null,
  val productId: String? = null,
  val basePlanId: String? = null,
  val offerId: String? = null,
  val displayName: String? = null,
  val displayPrice: String? = null,
  val price: Double? = null,
  val currencyCode: String? = null,
  val timestampMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PPurchaseRequest {
      val requestId = pigeonVar_list[0] as String?
      val platform = pigeonVar_list[1] as String?
      val productId = pigeonVar_list[2] as String?
      val basePlanId = pigeonVar_list[3] as String?
      val offerId = pigeonVar_list[4] as String?
      val displayName = pigeonVar_list[5] as String?
      val displayPrice = pigeonVar_list[6] as String?
      val price = pigeonVar_list[7] as Double?
      val currencyCode = pigeonVar_list[8] as String?
      val timestampMs = pigeonVar_list[9] as Long?
      return PPurchaseRequest(requestId, platform, productId, basePlanId, offerId, displayName, displayPrice, price, currencyCode, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      platform,
      productId,
      basePlanId,
      offerId,
      displayName,
      displayPrice,
      price,
      currencyCode,
      timestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PPurchaseRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PRestoreRequest (
  val requestId: String? = null,
  val platform: String? = null,
  val timestampMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PRestoreRequest {
      val requestId = pigeonVar_list[0] as String?
      val platform = pigeonVar_list[1] as String?
      val timestampMs = pigeonVar_list[2] as Long?
      return PRestoreRequest(requestId, platform, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      platform,
      timestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PRestoreRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PPurchaseResult (
  val type: String? = null,
  val message: String? = null,
  val productId: String? = null,
  val purchaseToken: String? = null,
  val orderId: String? = null,
  val transactionId: String? = null,
  val originalTransactionId: String? = null,
  val transactionJws: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PPurchaseResult {
      val type = pigeonVar_list[0] as String?
      val message = pigeonVar_list[1] as String?
      val productId = pigeonVar_list[2] as String?
      val purchaseToken = pigeonVar_list[3] as String?
      val orderId = pigeonVar_list[4] as String?
      val transactionId = pigeonVar_list[5] as String?
      val originalTransactionId = pigeonVar_list[6] as String?
      val transactionJws = pigeonVar_list[7] as String?
      return PPurchaseResult(type, message, productId, purchaseToken, orderId, transactionId, originalTransactionId, transactionJws)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      message,
      productId,
      purchaseToken,
      orderId,
      transactionId,
      originalTransactionId,
      transactionJws,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PPurchaseResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PRestoreResult (
  val type: String? = null,
  val restoredCount: Long? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PRestoreResult {
      val type = pigeonVar_list[0] as String?
      val restoredCount = pigeonVar_list[1] as Long?
      val message = pigeonVar_list[2] as String?
      return PRestoreResult(type, restoredCount, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      restoredCount,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PRestoreResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return NuxieBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class NuxieBridgePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PConfigureRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PTriggerRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PTriggerUpdate.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PFeatureAccess.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PFeatureCheckResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PFeatureUsageResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PProfileResponse.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PFeatureAccessChangedEvent.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PFlowLifecycleEvent.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PLogEvent.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PPurchaseRequest.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PRestoreRequest.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PPurchaseResult.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PRestoreResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PConfigureRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PTriggerRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PTriggerUpdate -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PFeatureAccess -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PFeatureCheckResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PFeatureUsageResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PProfileResponse -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PFeatureAccessChangedEvent -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is PFlowLifecycleEvent -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is PLogEvent -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is PPurchaseRequest -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is PRestoreRequest -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is PPurchaseResult -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is PRestoreResult -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PNuxieHostApi {
  fun configure(request: PConfigureRequest, callback: (Result<Unit>) -> Unit)
  fun shutdown(callback: (Result<Unit>) -> Unit)
  fun identify(distinctId: String, userProperties: Map<String?, Any?>?, userPropertiesSetOnce: Map<String?, Any?>?, callback: (Result<Unit>) -> Unit)
  fun reset(keepAnonymousId: Boolean, callback: (Result<Unit>) -> Unit)
  fun getDistinctId(callback: (Result<String>) -> Unit)
  fun getAnonymousId(callback: (Result<String>) -> Unit)
  fun getIsIdentified(callback: (Result<Boolean>) -> Unit)
  fun startTrigger(request: PTriggerRequest, callback: (Result<Unit>) -> Unit)
  fun cancelTrigger(requestId: String, callback: (Result<Unit>) -> Unit)
  fun showFlow(flowId: String, callback: (Result<Unit>) -> Unit)
  fun refreshProfile(callback: (Result<PProfileResponse>) -> Unit)
  fun hasFeature(featureId: String, requiredBalance: Long?, entityId: String?, callback: (Result<PFeatureAccess>) -> Unit)
  fun getCachedFeature(featureId: String, entityId: String?, callback: (Result<PFeatureAccess?>) -> Unit)
  fun checkFeature(featureId: String, requiredBalance: Long?, entityId: String?, callback: (Result<PFeatureCheckResult>) -> Unit)
  fun refreshFeature(featureId: String, requiredBalance: Long?, entityId: String?, callback: (Result<PFeatureCheckResult>) -> Unit)
  fun useFeature(featureId: String, amount: Double, entityId: String?, metadata: Map<String?, Any?>?, callback: (Result<Unit>) -> Unit)
  fun useFeatureAndWait(featureId: String, amount: Double, entityId: String?, setUsage: Boolean, metadata: Map<String?, Any?>?, callback: (Result<PFeatureUsageResult>) -> Unit)
  fun flushEvents(callback: (Result<Boolean>) -> Unit)
  fun getQueuedEventCount(callback: (Result<Long>) -> Unit)
  fun pauseEventQueue(callback: (Result<Unit>) -> Unit)
  fun resumeEventQueue(callback: (Result<Unit>) -> Unit)
  fun completePurchase(requestId: String, result: PPurchaseResult, callback: (Result<Unit>) -> Unit)
  fun completeRestore(requestId: String, result: PRestoreResult, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by PNuxieHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NuxieBridgePigeonCodec()
    }
    /** Sets up an instance of `PNuxieHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PNuxieHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PConfigureRequest
            api.configure(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.shutdown$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.shutdown{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.identify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val distinctIdArg = args[0] as String
            val userPropertiesArg = args[1] as Map<String?, Any?>?
            val userPropertiesSetOnceArg = args[2] as Map<String?, Any?>?
            api.identify(distinctIdArg, userPropertiesArg, userPropertiesSetOnceArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.reset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keepAnonymousIdArg = args[0] as Boolean
            api.reset(keepAnonymousIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.getDistinctId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDistinctId{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.getAnonymousId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAnonymousId{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.getIsIdentified$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getIsIdentified{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.startTrigger$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PTriggerRequest
            api.startTrigger(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.cancelTrigger$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            api.cancelTrigger(requestIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.showFlow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val flowIdArg = args[0] as String
            api.showFlow(flowIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.refreshProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.refreshProfile{ result: Result<PProfileResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.hasFeature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureIdArg = args[0] as String
            val requiredBalanceArg = args[1] as Long?
            val entityIdArg = args[2] as String?
            api.hasFeature(featureIdArg, requiredBalanceArg, entityIdArg) { result: Result<PFeatureAccess> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.getCachedFeature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureIdArg = args[0] as String
            val entityIdArg = args[1] as String?
            api.getCachedFeature(featureIdArg, entityIdArg) { result: Result<PFeatureAccess?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.checkFeature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureIdArg = args[0] as String
            val requiredBalanceArg = args[1] as Long?
            val entityIdArg = args[2] as String?
            api.checkFeature(featureIdArg, requiredBalanceArg, entityIdArg) { result: Result<PFeatureCheckResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.refreshFeature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureIdArg = args[0] as String
            val requiredBalanceArg = args[1] as Long?
            val entityIdArg = args[2] as String?
            api.refreshFeature(featureIdArg, requiredBalanceArg, entityIdArg) { result: Result<PFeatureCheckResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.useFeature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureIdArg = args[0] as String
            val amountArg = args[1] as Double
            val entityIdArg = args[2] as String?
            val metadataArg = args[3] as Map<String?, Any?>?
            api.useFeature(featureIdArg, amountArg, entityIdArg, metadataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.useFeatureAndWait$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureIdArg = args[0] as String
            val amountArg = args[1] as Double
            val entityIdArg = args[2] as String?
            val setUsageArg = args[3] as Boolean
            val metadataArg = args[4] as Map<String?, Any?>?
            api.useFeatureAndWait(featureIdArg, amountArg, entityIdArg, setUsageArg, metadataArg) { result: Result<PFeatureUsageResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.flushEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.flushEvents{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.getQueuedEventCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getQueuedEventCount{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.pauseEventQueue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.pauseEventQueue{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.resumeEventQueue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.resumeEventQueue{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.completePurchase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val resultArg = args[1] as PPurchaseResult
            api.completePurchase(requestIdArg, resultArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.completeRestore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val resultArg = args[1] as PRestoreResult
            api.completeRestore(requestIdArg, resultArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PNuxieFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PNuxieFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      NuxieBridgePigeonCodec()
    }
  }
  fun onTriggerUpdate(eventArg: PTriggerUpdate, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onTriggerUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NuxieBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onFeatureAccessChanged(eventArg: PFeatureAccessChangedEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onFeatureAccessChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NuxieBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onFlowLifecycle(eventArg: PFlowLifecycleEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onFlowLifecycle$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NuxieBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onLog(eventArg: PLogEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onLog$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NuxieBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPurchaseRequest(requestArg: PPurchaseRequest, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onPurchaseRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NuxieBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onRestoreRequest(requestArg: PRestoreRequest, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onRestoreRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NuxieBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
