// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.nuxie.flutter.nativeplugin

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NuxieBridgePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class PConfigureRequest (
  val apiKey: String? = null,
  val wrapperVersion: String? = null,
  val usingPurchaseController: Boolean? = null,
  val environment: String? = null,
  val logLevel: String? = null,
  val enableConsoleLogging: Boolean? = null,
  val redactSensitiveData: Boolean? = null,
  val localeIdentifier: String? = null,
  val purchaseHandlingMode: String? = null,
  val testStoreEnabled: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PConfigureRequest {
      val apiKey = pigeonVar_list[0] as String?
      val wrapperVersion = pigeonVar_list[1] as String?
      val usingPurchaseController = pigeonVar_list[2] as Boolean?
      val environment = pigeonVar_list[3] as String?
      val logLevel = pigeonVar_list[4] as String?
      val enableConsoleLogging = pigeonVar_list[5] as Boolean?
      val redactSensitiveData = pigeonVar_list[6] as Boolean?
      val localeIdentifier = pigeonVar_list[7] as String?
      val purchaseHandlingMode = pigeonVar_list[8] as String?
      val testStoreEnabled = pigeonVar_list[9] as Boolean?
      return PConfigureRequest(apiKey, wrapperVersion, usingPurchaseController, environment, logLevel, enableConsoleLogging, redactSensitiveData, localeIdentifier, purchaseHandlingMode, testStoreEnabled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      wrapperVersion,
      usingPurchaseController,
      environment,
      logLevel,
      enableConsoleLogging,
      redactSensitiveData,
      localeIdentifier,
      purchaseHandlingMode,
      testStoreEnabled,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PConfigureRequest
    return NuxieBridgePigeonUtils.deepEquals(this.apiKey, other.apiKey) && NuxieBridgePigeonUtils.deepEquals(this.wrapperVersion, other.wrapperVersion) && NuxieBridgePigeonUtils.deepEquals(this.usingPurchaseController, other.usingPurchaseController) && NuxieBridgePigeonUtils.deepEquals(this.environment, other.environment) && NuxieBridgePigeonUtils.deepEquals(this.logLevel, other.logLevel) && NuxieBridgePigeonUtils.deepEquals(this.enableConsoleLogging, other.enableConsoleLogging) && NuxieBridgePigeonUtils.deepEquals(this.redactSensitiveData, other.redactSensitiveData) && NuxieBridgePigeonUtils.deepEquals(this.localeIdentifier, other.localeIdentifier) && NuxieBridgePigeonUtils.deepEquals(this.purchaseHandlingMode, other.purchaseHandlingMode) && NuxieBridgePigeonUtils.deepEquals(this.testStoreEnabled, other.testStoreEnabled)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.apiKey)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.wrapperVersion)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.usingPurchaseController)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.environment)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.logLevel)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.enableConsoleLogging)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.redactSensitiveData)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.localeIdentifier)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.purchaseHandlingMode)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.testStoreEnabled)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PFeatureAccess (
  val allowed: Boolean? = null,
  val unlimited: Boolean? = null,
  val balance: Double? = null,
  val type: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PFeatureAccess {
      val allowed = pigeonVar_list[0] as Boolean?
      val unlimited = pigeonVar_list[1] as Boolean?
      val balance = pigeonVar_list[2] as Double?
      val type = pigeonVar_list[3] as String?
      return PFeatureAccess(allowed, unlimited, balance, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      allowed,
      unlimited,
      balance,
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PFeatureAccess
    return NuxieBridgePigeonUtils.deepEquals(this.allowed, other.allowed) && NuxieBridgePigeonUtils.deepEquals(this.unlimited, other.unlimited) && NuxieBridgePigeonUtils.deepEquals(this.balance, other.balance) && NuxieBridgePigeonUtils.deepEquals(this.type, other.type)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.allowed)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.unlimited)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.balance)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.type)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PFeatureUsageResult (
  val success: Boolean? = null,
  val featureId: String? = null,
  val amountUsed: Double? = null,
  val message: String? = null,
  val usageCurrent: Double? = null,
  val usageLimit: Double? = null,
  val usageRemaining: Double? = null,
  val authoritativeAccess: PFeatureAccess? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PFeatureUsageResult {
      val success = pigeonVar_list[0] as Boolean?
      val featureId = pigeonVar_list[1] as String?
      val amountUsed = pigeonVar_list[2] as Double?
      val message = pigeonVar_list[3] as String?
      val usageCurrent = pigeonVar_list[4] as Double?
      val usageLimit = pigeonVar_list[5] as Double?
      val usageRemaining = pigeonVar_list[6] as Double?
      val authoritativeAccess = pigeonVar_list[7] as PFeatureAccess?
      return PFeatureUsageResult(success, featureId, amountUsed, message, usageCurrent, usageLimit, usageRemaining, authoritativeAccess)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      featureId,
      amountUsed,
      message,
      usageCurrent,
      usageLimit,
      usageRemaining,
      authoritativeAccess,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PFeatureUsageResult
    return NuxieBridgePigeonUtils.deepEquals(this.success, other.success) && NuxieBridgePigeonUtils.deepEquals(this.featureId, other.featureId) && NuxieBridgePigeonUtils.deepEquals(this.amountUsed, other.amountUsed) && NuxieBridgePigeonUtils.deepEquals(this.message, other.message) && NuxieBridgePigeonUtils.deepEquals(this.usageCurrent, other.usageCurrent) && NuxieBridgePigeonUtils.deepEquals(this.usageLimit, other.usageLimit) && NuxieBridgePigeonUtils.deepEquals(this.usageRemaining, other.usageRemaining) && NuxieBridgePigeonUtils.deepEquals(this.authoritativeAccess, other.authoritativeAccess)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.success)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.featureId)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.amountUsed)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.message)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.usageCurrent)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.usageLimit)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.usageRemaining)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.authoritativeAccess)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PFeatureAccessChangedEvent (
  val featureId: String? = null,
  val from: PFeatureAccess? = null,
  val to: PFeatureAccess? = null,
  val timestampMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PFeatureAccessChangedEvent {
      val featureId = pigeonVar_list[0] as String?
      val from = pigeonVar_list[1] as PFeatureAccess?
      val to = pigeonVar_list[2] as PFeatureAccess?
      val timestampMs = pigeonVar_list[3] as Long?
      return PFeatureAccessChangedEvent(featureId, from, to, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      featureId,
      from,
      to,
      timestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PFeatureAccessChangedEvent
    return NuxieBridgePigeonUtils.deepEquals(this.featureId, other.featureId) && NuxieBridgePigeonUtils.deepEquals(this.from, other.from) && NuxieBridgePigeonUtils.deepEquals(this.to, other.to) && NuxieBridgePigeonUtils.deepEquals(this.timestampMs, other.timestampMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.featureId)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.from)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.to)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.timestampMs)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PExperienceRef (
  val experienceId: String? = null,
  val experienceVersion: String? = null,
  val journeyId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PExperienceRef {
      val experienceId = pigeonVar_list[0] as String?
      val experienceVersion = pigeonVar_list[1] as String?
      val journeyId = pigeonVar_list[2] as String?
      return PExperienceRef(experienceId, experienceVersion, journeyId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      experienceId,
      experienceVersion,
      journeyId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PExperienceRef
    return NuxieBridgePigeonUtils.deepEquals(this.experienceId, other.experienceId) && NuxieBridgePigeonUtils.deepEquals(this.experienceVersion, other.experienceVersion) && NuxieBridgePigeonUtils.deepEquals(this.journeyId, other.journeyId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.experienceId)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.experienceVersion)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.journeyId)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PAppAction (
  val name: String? = null,
  val payload: Map<String?, Any?>? = null,
  val experience: PExperienceRef? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PAppAction {
      val name = pigeonVar_list[0] as String?
      val payload = pigeonVar_list[1] as Map<String?, Any?>?
      val experience = pigeonVar_list[2] as PExperienceRef?
      return PAppAction(name, payload, experience)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      payload,
      experience,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PAppAction
    return NuxieBridgePigeonUtils.deepEquals(this.name, other.name) && NuxieBridgePigeonUtils.deepEquals(this.payload, other.payload) && NuxieBridgePigeonUtils.deepEquals(this.experience, other.experience)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.name)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.payload)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.experience)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PActivityInfo (
  val schemaVersion: Long? = null,
  val id: String? = null,
  val timestampMs: Long? = null,
  val receivedAtMs: Long? = null,
  val name: String? = null,
  val properties: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PActivityInfo {
      val schemaVersion = pigeonVar_list[0] as Long?
      val id = pigeonVar_list[1] as String?
      val timestampMs = pigeonVar_list[2] as Long?
      val receivedAtMs = pigeonVar_list[3] as Long?
      val name = pigeonVar_list[4] as String?
      val properties = pigeonVar_list[5] as Map<String?, Any?>?
      return PActivityInfo(schemaVersion, id, timestampMs, receivedAtMs, name, properties)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      schemaVersion,
      id,
      timestampMs,
      receivedAtMs,
      name,
      properties,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PActivityInfo
    return NuxieBridgePigeonUtils.deepEquals(this.schemaVersion, other.schemaVersion) && NuxieBridgePigeonUtils.deepEquals(this.id, other.id) && NuxieBridgePigeonUtils.deepEquals(this.timestampMs, other.timestampMs) && NuxieBridgePigeonUtils.deepEquals(this.receivedAtMs, other.receivedAtMs) && NuxieBridgePigeonUtils.deepEquals(this.name, other.name) && NuxieBridgePigeonUtils.deepEquals(this.properties, other.properties)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.schemaVersion)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.id)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.timestampMs)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.receivedAtMs)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.name)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.properties)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PPurchaseRequest (
  val requestId: String? = null,
  val platform: String? = null,
  val productId: String? = null,
  val storeProductId: String? = null,
  val basePlanId: String? = null,
  val purchaseOptionId: String? = null,
  val offerId: String? = null,
  val placementId: String? = null,
  val displayName: String? = null,
  val displayPrice: String? = null,
  val timestampMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PPurchaseRequest {
      val requestId = pigeonVar_list[0] as String?
      val platform = pigeonVar_list[1] as String?
      val productId = pigeonVar_list[2] as String?
      val storeProductId = pigeonVar_list[3] as String?
      val basePlanId = pigeonVar_list[4] as String?
      val purchaseOptionId = pigeonVar_list[5] as String?
      val offerId = pigeonVar_list[6] as String?
      val placementId = pigeonVar_list[7] as String?
      val displayName = pigeonVar_list[8] as String?
      val displayPrice = pigeonVar_list[9] as String?
      val timestampMs = pigeonVar_list[10] as Long?
      return PPurchaseRequest(requestId, platform, productId, storeProductId, basePlanId, purchaseOptionId, offerId, placementId, displayName, displayPrice, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      platform,
      productId,
      storeProductId,
      basePlanId,
      purchaseOptionId,
      offerId,
      placementId,
      displayName,
      displayPrice,
      timestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PPurchaseRequest
    return NuxieBridgePigeonUtils.deepEquals(this.requestId, other.requestId) && NuxieBridgePigeonUtils.deepEquals(this.platform, other.platform) && NuxieBridgePigeonUtils.deepEquals(this.productId, other.productId) && NuxieBridgePigeonUtils.deepEquals(this.storeProductId, other.storeProductId) && NuxieBridgePigeonUtils.deepEquals(this.basePlanId, other.basePlanId) && NuxieBridgePigeonUtils.deepEquals(this.purchaseOptionId, other.purchaseOptionId) && NuxieBridgePigeonUtils.deepEquals(this.offerId, other.offerId) && NuxieBridgePigeonUtils.deepEquals(this.placementId, other.placementId) && NuxieBridgePigeonUtils.deepEquals(this.displayName, other.displayName) && NuxieBridgePigeonUtils.deepEquals(this.displayPrice, other.displayPrice) && NuxieBridgePigeonUtils.deepEquals(this.timestampMs, other.timestampMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.requestId)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.platform)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.productId)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.storeProductId)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.basePlanId)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.purchaseOptionId)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.offerId)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.placementId)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.displayName)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.displayPrice)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.timestampMs)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PRestoreRequest (
  val requestId: String? = null,
  val platform: String? = null,
  val timestampMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PRestoreRequest {
      val requestId = pigeonVar_list[0] as String?
      val platform = pigeonVar_list[1] as String?
      val timestampMs = pigeonVar_list[2] as Long?
      return PRestoreRequest(requestId, platform, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      platform,
      timestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PRestoreRequest
    return NuxieBridgePigeonUtils.deepEquals(this.requestId, other.requestId) && NuxieBridgePigeonUtils.deepEquals(this.platform, other.platform) && NuxieBridgePigeonUtils.deepEquals(this.timestampMs, other.timestampMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.requestId)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.platform)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.timestampMs)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PPurchaseResult (
  val type: String? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PPurchaseResult {
      val type = pigeonVar_list[0] as String?
      val message = pigeonVar_list[1] as String?
      return PPurchaseResult(type, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PPurchaseResult
    return NuxieBridgePigeonUtils.deepEquals(this.type, other.type) && NuxieBridgePigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.type)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.message)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PRestoreResult (
  val type: String? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PRestoreResult {
      val type = pigeonVar_list[0] as String?
      val message = pigeonVar_list[1] as String?
      return PRestoreResult(type, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PRestoreResult
    return NuxieBridgePigeonUtils.deepEquals(this.type, other.type) && NuxieBridgePigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.type)
    result = 31 * result + NuxieBridgePigeonUtils.deepHash(this.message)
    return result
  }
}
private open class NuxieBridgePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PConfigureRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PFeatureAccess.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PFeatureUsageResult.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PFeatureAccessChangedEvent.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PExperienceRef.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PAppAction.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PActivityInfo.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PPurchaseRequest.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PRestoreRequest.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PPurchaseResult.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PRestoreResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PConfigureRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PFeatureAccess -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PFeatureUsageResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PFeatureAccessChangedEvent -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PExperienceRef -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PAppAction -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PActivityInfo -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PPurchaseRequest -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is PRestoreRequest -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is PPurchaseResult -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is PRestoreResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PNuxieHostApi {
  fun configure(request: PConfigureRequest, callback: (Result<Unit>) -> Unit)
  fun shutdown(callback: (Result<Unit>) -> Unit)
  fun identify(distinctId: String, userProperties: Map<String?, Any?>?, userPropertiesSetOnce: Map<String?, Any?>?, callback: (Result<Unit>) -> Unit)
  fun reset(keepAnonymousId: Boolean, callback: (Result<Unit>) -> Unit)
  fun getDistinctId(callback: (Result<String>) -> Unit)
  fun getAnonymousId(callback: (Result<String>) -> Unit)
  fun getIsIdentified(callback: (Result<Boolean>) -> Unit)
  fun trigger(event: String, properties: Map<String?, Any?>?)
  fun dismiss(callback: (Result<Unit>) -> Unit)
  fun setLocaleIdentifier(localeIdentifier: String?, callback: (Result<Unit>) -> Unit)
  fun hasFeature(featureId: String, requiredBalance: Double, entityId: String?, policy: String, callback: (Result<PFeatureAccess>) -> Unit)
  fun useFeature(featureId: String, amount: Double, entityId: String?, metadata: Map<String?, Any?>?)
  fun useFeatureAndWait(featureId: String, amount: Double, entityId: String?, setUsage: Boolean, metadata: Map<String?, Any?>?, callback: (Result<PFeatureUsageResult>) -> Unit)
  fun completePurchase(requestId: String, result: PPurchaseResult)
  fun completeRestore(requestId: String, result: PRestoreResult)

  companion object {
    /** The codec used by PNuxieHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NuxieBridgePigeonCodec()
    }
    /** Sets up an instance of `PNuxieHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PNuxieHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PConfigureRequest
            api.configure(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.shutdown$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.shutdown{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.identify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val distinctIdArg = args[0] as String
            val userPropertiesArg = args[1] as Map<String?, Any?>?
            val userPropertiesSetOnceArg = args[2] as Map<String?, Any?>?
            api.identify(distinctIdArg, userPropertiesArg, userPropertiesSetOnceArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.reset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keepAnonymousIdArg = args[0] as Boolean
            api.reset(keepAnonymousIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.getDistinctId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDistinctId{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.getAnonymousId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAnonymousId{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.getIsIdentified$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getIsIdentified{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.trigger$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventArg = args[0] as String
            val propertiesArg = args[1] as Map<String?, Any?>?
            val wrapped: List<Any?> = try {
              api.trigger(eventArg, propertiesArg)
              listOf(null)
            } catch (exception: Throwable) {
              NuxieBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.dismiss$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.dismiss{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.setLocaleIdentifier$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val localeIdentifierArg = args[0] as String?
            api.setLocaleIdentifier(localeIdentifierArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(NuxieBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.hasFeature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureIdArg = args[0] as String
            val requiredBalanceArg = args[1] as Double
            val entityIdArg = args[2] as String?
            val policyArg = args[3] as String
            api.hasFeature(featureIdArg, requiredBalanceArg, entityIdArg, policyArg) { result: Result<PFeatureAccess> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.useFeature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureIdArg = args[0] as String
            val amountArg = args[1] as Double
            val entityIdArg = args[2] as String?
            val metadataArg = args[3] as Map<String?, Any?>?
            val wrapped: List<Any?> = try {
              api.useFeature(featureIdArg, amountArg, entityIdArg, metadataArg)
              listOf(null)
            } catch (exception: Throwable) {
              NuxieBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.useFeatureAndWait$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureIdArg = args[0] as String
            val amountArg = args[1] as Double
            val entityIdArg = args[2] as String?
            val setUsageArg = args[3] as Boolean
            val metadataArg = args[4] as Map<String?, Any?>?
            api.useFeatureAndWait(featureIdArg, amountArg, entityIdArg, setUsageArg, metadataArg) { result: Result<PFeatureUsageResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NuxieBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NuxieBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.completePurchase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val resultArg = args[1] as PPurchaseResult
            val wrapped: List<Any?> = try {
              api.completePurchase(requestIdArg, resultArg)
              listOf(null)
            } catch (exception: Throwable) {
              NuxieBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.completeRestore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val resultArg = args[1] as PRestoreResult
            val wrapped: List<Any?> = try {
              api.completeRestore(requestIdArg, resultArg)
              listOf(null)
            } catch (exception: Throwable) {
              NuxieBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PNuxieFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PNuxieFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      NuxieBridgePigeonCodec()
    }
  }
  fun onFeatureAccessChanged(eventArg: PFeatureAccessChangedEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onFeatureAccessChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NuxieBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onActivity(activityArg: PActivityInfo, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onActivity$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(activityArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NuxieBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAppAction(actionArg: PAppAction, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onAppAction$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(actionArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NuxieBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPurchaseRequest(requestArg: PPurchaseRequest, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onPurchaseRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NuxieBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onRestoreRequest(requestArg: PRestoreRequest, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onRestoreRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NuxieBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
